port: 18080
worker_num: 4
build_dag_each_worker: false
grpc_gateway_port: 9999
dag:
    is_thread_op: false
    client_type: brpc
    retry: 1
    use_profile: false
    tracer:
        interval_s: 10
