rpc_port: 18080
worker_num: 4
build_dag_each_worker: false
dag:
    is_thread_op: true
    retry: 1
    use_profile: false
op:
    bow:
        concurrency: 2
        remote_service_conf:
            client_type: brpc
            model_config: imdb_bow_model
            devices: ""
            rpc_port : 9393 
    cnn:
        concurrency: 2
        remote_service_conf:
            client_type: brpc
            model_config: imdb_cnn_model
            devices: ""
            rpc_port : 9292
